---
sudo: required
services:
- docker
language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/chad-autry/wac-python
script:
- docker build -t chadautry/wac-pythong:latest .
- if [[ ! -z "$TRAVIS_TAG" ]]; then docker tag chadautry/wac-python:latest chadautry/wac-python:$TRAVIS_TAG ; fi
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push chadautry/wac-python